AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  NepoSpot

  Celebrity background analyzer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  NepoSpotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: build/
      Handler: bootstrap.is.the.handler
      Runtime: provided.al2
      Timeout: 60
      Architectures:
        - x86_64
      Events:
        NepoSpot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NepoSpotApi:
    Description: "API Gateway endpoint URL for Prod stage for NepoSpot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  NepoSpotFunction:
    Description: "NepoSpot Lambda Function ARN"
    Value: !GetAtt NepoSpotFunction.Arn
  NepoSpotFunctionIamRole:
    Description: "Implicit IAM Role created for NepoSpot function"
    Value: !GetAtt NepoSpotFunctionRole.Arn
